### PR TITLE
Some JL edits - requirements

### PR DESCRIPTION
**Pull request by jlivingood**
Last of my edits before the IETF-106 draft cutoff date. I think we can keep iterating here after the cutoff. 

Ref Issues:
https://github.com/alex-nicat/ietf-dprive-phase2-requirements/issues/7

### CODE REVIEW

**Comment by jlivingood** [comment]
Not yet my final edits! ;-)

**Comment by bjovereinder** [comment]
Should we remove the distinction between root/tld/sld authoritative name servers and their priority/risk?

**Comment by bjovereinder** [comment]
DNS software (currently) doesn't make the distinction between root, tld or sld, and it seems to me more an operational than protocol requirement?

**Comment by jlivingood** [comment]
IMO the operation of SLD, TLD, root are all so very different. So I think we should acknowledge that in the requirements, especially as I suspect they differ by each category and each will also implement on different timeframes and different manners.

**Comment by jlivingood** [comment]
So IMO leave it in as WG item for discussion at 106 & make an explicit point of discussion for our slides

**Comment by bjovereinder** [comment]
Okay. I understand, maybe I am too focussed on protocol requirements rather than general req for ADoT. 

— Benno 

Verstuurd vanaf mijn iPhone

**Pull request merged**
